### ISSUE TITLE
Channel is disconnected if requests are canceled

### ISSUE THREAD

**Issue by Weshnaw** [epwalsh/batched-fn#25]
I'm having an issue using gRPC where if the request is cancelled prematurely it kills the batched_fn, and will only be resolved by restarting the service completely, and I was wondering if there is a way to re-initialize the thread if it disconnects at runtime? 

I'm fairly certain it is also similar if not the same issue as this poster from another repo:
https://github.com/epwalsh/rust-dl-webserver/issues/60

Steps to reproduce with gRPC:
1. send gRPC request to a endpoint that relies on batched_fn!(...)
2. cancel the request before it completes
3. retry the request (it should be failing)
Note: this could be either during or after the batched_fn! was initialized, either one if the request is canceled it breaks the batched_fn for the rest of the program's lifespan

```rust
// Uses rust_bert for SentenceEmbeddingsModel
async fn encode_setence(input: String) -> Result<Vec<f32>, batched_fn::Error> {
    let batch_encode = batched_fn! {
        handler = |batch: Vec<String>, model: &SentenceEmbeddingsModel| -> Vec<Vec<f32>> {
            let span = info_span!("batch_handler");
            let _enter = span.enter();
            debug!("{:?}", batch);
            model.encode(&batch).unwrap()
        };
        config = {
            max_batch_size: 16,
            max_delay: 100,
            channel_cap: Some(20),
        };
        context = {
            model: {
                let span = info_span!("batch_context");
                let _context_enter = span.enter();
                info!("Initializing Model...");
                let span = info_span!("model_load");
                let _load_enter = span.enter();
                info!("Cuda: {}", Cuda::cudnn_is_available());
                info!("Model: {}", LOCAL_MODEL);
                SentenceEmbeddingsBuilder::local(LOCAL_MODEL)
                    .with_device(tch::Device::cuda_if_available())
                    .create_model()
                    .context("Failed to initialize embedding model").unwrap()
            },
        };
    };

    batch_encode(input).await
}
```

```rust
#[tonic::async_trait]
impl Encoder for MyEncoder {
    #[instrument(skip_all)]
    async fn encode_sentence(
        &self,
        request: Request<SentenceRequest>,
    ) -> Result<Response<EmbeddingReply>, Status> {
        info!("EncodeSentence request recieved...");

        let data = encode_setence(request.into_inner().sentence)
            .await
            .map_err(|err| {
                warn!("{:?}", err);
                Status::internal("batch encoder broken")
            })?;

        let reply = EmbeddingReply { data };

        Ok(Response::new(reply))
    }
}
```

```
2024-03-05T17:13:50.133775Z  INFO example: Initializing Tonic...
2024-03-05T17:13:50.134101Z  INFO tonic_startup: example: address: [::1]:50051
2024-03-05T17:13:50.134206Z  INFO tonic_startup: example: Initializing Tonic Reflection...
2024-03-05T17:13:50.135073Z  INFO example: Tonic Initialized...
2024-03-05T17:13:56.507081Z  INFO encode_sentence: example: EncodeSentence request received...
2024-03-05T17:13:56.507693Z  INFO batch_context: example: Initializing Model...
2024-03-05T17:13:56.524687Z  INFO batch_context:model_load: example: Cuda: true
2024-03-05T17:14:00.489850Z  INFO encode_sentence: example: EncodeSentence request received...
2024-03-05T17:14:01.497046Z  INFO encode_sentence: example: EncodeSentence request received...
2024-03-05T17:14:02.012228Z  INFO encode_sentence: example: EncodeSentence request received...
thread '<unnamed>' panicked at example\src\main.rs:85:24:
Channel from calling thread disconnected: "SendError(..)"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-03-05T17:14:04.710488Z  INFO encode_sentence: example: EncodeSentence request received...
2024-03-05T17:14:04.710735Z  WARN encode_sentence: example: Disconnected
```

**Comment by epwalsh** [comment]
Hey @Weshnaw, does indeed look like the same issue. Could run with `RUST_BACKTRACE=1` and send me the output?

**Comment by Weshnaw** [comment]
```
2024-03-05T20:18:40.725817Z  INFO example: Initializing Tonic...
2024-03-05T20:18:40.726117Z  INFO tonic_startup: example: address: [::1]:50051
2024-03-05T20:18:40.726217Z  INFO tonic_startup: example: Initializing Tonic Reflection...
2024-03-05T20:18:40.727112Z  INFO example: Tonic Initialized...
2024-03-05T20:18:46.316296Z  INFO encode_sentence: example: EncodeSentence request received...
2024-03-05T20:18:46.316826Z  INFO batch_context: example: Initializing Model...
2024-03-05T20:18:46.370480Z  INFO batch_context:model_load: example: Cuda: true
2024-03-05T20:18:46.370635Z  INFO batch_context:model_load: example: Model: resources/instructor-xl
2024-03-05T20:18:48.616130Z  INFO encode_sentence: example: EncodeSentence request received...
thread '<unnamed>' panicked at example\src\main.rs:77:24:
Channel from calling thread disconnected: "SendError(..)"
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library\core\src\panicking.rs:72
   2: core::result::unwrap_failed
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library\core\src\result.rs:1649
   3: enum2$<core::result::Result<tuple$<>,flume::SendError<alloc::vec::Vec<f32,alloc::alloc::Global> > > >::expect<tuple$<>,flume::SendError<alloc::vec::Vec<f32,alloc::alloc::Global> > >
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1\library\core\src\result.rs:1030
   4: example::encode_setence::async_fn$0::BATCHED_FN::closure$0::closure$0
             at C:\Users\bfall\.cargo\registry\src\index.crates.io-6f17d22bba15001f\batched-fn-0.2.4\src\lib.rs:353
   5: core::hint::black_box
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1\library\core\src\hint.rs:334
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
2024-03-05T20:18:54.889290Z  INFO encode_sentence: example: EncodeSentence request received...
2024-03-05T20:18:54.889483Z  WARN encode_sentence: example: Disconnected
```

**Comment by Weshnaw** [comment]
I debugged this a bit myself; and figured out why the whole thread crashes when the requests are canceled:
```rust
for (output, mut result_tx) in batch_output.into_iter().zip(batch_txs) {
    result_tx.send(output).expect("Channel from calling thread disconnected");
}
```
https://github.com/epwalsh/batched-fn/blob/main/src/lib.rs#L347-L349 

this expect crashes the thread because gRPC drops the calling thread if the request is canceled; this might just be my own opinion but I think changing this to
```rust
for (output, mut result_tx) in batch_output.into_iter().zip(batch_txs) {
    result_tx.try_send(output).ok()
}
```
should be fine for most cases
